# Site settings
title: Eat. Think. Du.
header-img: img/pic5.jpg
email: erica.c.du@gmail.com
description: "food + ideas + adventure"
baseurl: ""
url: "http://eatthinkdu.com"
# url: "http://localhost:4000"
twitter_username:  
github_username:  
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
analytics:
  provider: google
  google:
    tracking_id: 'UA-62872110-2'